---

- name: Install AWS cli
  raw: dnf install -y awscli

- name: Install vim
  raw: dnf install -y vim

- name: Install VS Code
  raw: rpm --import https://packages.microsoft.com/keys/microsoft.asc && sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo' && dnf check-update && dnf install -y code

- name: Install terminals
  raw: dnf install -y terminator roxterm
