---

- name: Install AWS cli
  raw: dnf install -y awscli

- name: Create AWS cli config dir
  file:
    path: /home/roger/.aws
    owner: roger
    group: roger
    mode: 0755
    state: directory

- name: Create AWS cli config file
  template:
    src: aws/config
    dest: /home/roger/.aws/config
    owner: roger
    group: roger
    mode: 0600
    force: no

- name: Create AWS cli credentials file
  template:
    src: aws/credentials
    dest: /home/roger/.aws/credentials
    owner: roger
    group: roger
    mode: 0600
    force: no

- name: Install vim
  raw: dnf install -y vim

- name: Install VS Code
  raw: rpm --import https://packages.microsoft.com/keys/microsoft.asc && sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo' && dnf check-update && dnf install -y code

- name: Install terminals
  raw: dnf install -y terminator roxterm

- name: Install terminal color schemes
  raw: rm -rf /tmp/iTerm2-Color-Schemes && git clone https://github.com/mbadolato/iTerm2-Color-Schemes.git /tmp/iTerm2-Color-Schemes && cp /tmp/iTerm2-Color-Schemes/konsole/*.colorscheme /usr/share/konsole/

- name: Install bash color schemes
  template:
    src: .bash_colors
    dest: /home/roger/.bash_colors
    owner: roger
    group: roger

- name: Make sure bash color schemes are loaded
  lineinfile:
    path: /home/roger/.bashrc
    line: 'source ~/.bash_colors'
    owner: roger
    group: roger
